// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PruebaTecnica_Multitenant.API.Data;

#nullable disable

namespace PruebaTecnica_Multitenant.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Organizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("organizacion", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.OrganizacionUsuario", b =>
                {
                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("OrganizacionId", "UsuarioId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("organizaciones_usuarios", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("prioridad", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_id");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_limite");

                    b.Property<Guid>("OrganizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacion_id");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("integer")
                        .HasColumnName("prioridad_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("OrganizacionId");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tarea", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.OrganizacionUsuario", b =>
                {
                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Organizacion", "Organizacion")
                        .WithMany("OrganizacionesUsuarios")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Rol", "Rol")
                        .WithMany("OrganizacionesUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Usuario", "Usuario")
                        .WithMany("OrganizacionesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Tarea", b =>
                {
                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Estado", "Estado")
                        .WithMany("Tareas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Organizacion", "Organizacion")
                        .WithMany("Tareas")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Prioridad", "Prioridad")
                        .WithMany("Tareas")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnica_Multitenant.API.Models.Usuario", "Usuario")
                        .WithMany("Tareas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Organizacion");

                    b.Navigation("Prioridad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Estado", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Organizacion", b =>
                {
                    b.Navigation("OrganizacionesUsuarios");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Prioridad", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Rol", b =>
                {
                    b.Navigation("OrganizacionesUsuarios");
                });

            modelBuilder.Entity("PruebaTecnica_Multitenant.API.Models.Usuario", b =>
                {
                    b.Navigation("OrganizacionesUsuarios");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
